(function() {var implementors = {};
implementors["db"] = ["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"db/kv/struct.CompactionProfile.html\" title=\"struct db::kv::CompactionProfile\">CompactionProfile</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"db/kv/enum.Location.html\" title=\"enum db::kv::Location\">Location</a>",];
implementors["keys"] = ["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"keys/enum.Type.html\" title=\"enum keys::Type\">Type</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"keys/enum.Network.html\" title=\"enum keys::Network\">Network</a>",];
implementors["message"] = ["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"message/common/enum.InventoryType.html\" title=\"enum message::common::InventoryType\">InventoryType</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"message/common/struct.IpAddress.html\" title=\"struct message::common::IpAddress\">IpAddress</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"message/common/struct.Port.html\" title=\"struct message::common::Port\">Port</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"message/struct.Services.html\" title=\"struct message::Services\">Services</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"message/types/enum.FilterFlags.html\" title=\"enum message::types::FilterFlags\">FilterFlags</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"message/types/reject/enum.RejectCode.html\" title=\"enum message::types::reject::RejectCode\">RejectCode</a>",];
implementors["miner"] = ["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"miner/enum.MemoryPoolOrderingStrategy.html\" title=\"enum miner::MemoryPoolOrderingStrategy\">OrderingStrategy</a>",];
implementors["network"] = ["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"network/struct.Deployment.html\" title=\"struct network::Deployment\">Deployment</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"network/enum.Network.html\" title=\"enum network::Network\">Network</a>",];
implementors["p2p"] = ["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"p2p/enum.InternetProtocol.html\" title=\"enum p2p::InternetProtocol\">InternetProtocol</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"p2p/enum.Direction.html\" title=\"enum p2p::Direction\">Direction</a>",];
implementors["primitives"] = ["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"primitives/compact/struct.Compact.html\" title=\"struct primitives::compact::Compact\">Compact</a>",];
implementors["rpc"] = ["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"rpc/v1/types/enum.BlockTemplateRequestMode.html\" title=\"enum rpc::v1::types::BlockTemplateRequestMode\">BlockTemplateRequestMode</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"rpc/v1/types/struct.U256.html\" title=\"struct rpc::v1::types::U256\">U256</a>",];
implementors["script"] = ["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"script/struct.Num.html\" title=\"struct script::Num\">Num</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"script/enum.Opcode.html\" title=\"enum script::Opcode\">Opcode</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"script/enum.SignatureVersion.html\" title=\"enum script::SignatureVersion\">SignatureVersion</a>",];
implementors["serialization"] = ["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"serialization/struct.CompactInteger.html\" title=\"struct serialization::CompactInteger\">CompactInteger</a>",];
implementors["verification"] = ["impl&lt;'a&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"verification/struct.CanonBlock.html\" title=\"struct verification::CanonBlock\">CanonBlock</a>&lt;'a&gt;","impl&lt;'a&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"verification/struct.CanonHeader.html\" title=\"struct verification::CanonHeader\">CanonHeader</a>&lt;'a&gt;","impl&lt;'a&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"verification/struct.CanonTransaction.html\" title=\"struct verification::CanonTransaction\">CanonTransaction</a>&lt;'a&gt;","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"verification/enum.VerificationLevel.html\" title=\"enum verification::VerificationLevel\">VerificationLevel</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
